# Generated by Django 2.1.5 on 2019-10-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_festa', models.DateField()),
                ('hora_inicio', models.DateField()),
                ('hora_termino', models.DateField()),
                ('valor_cobrado', models.CharField(choices=[('Moeda', 'Moeda'), ('Cedula', 'Cedula')], default='Moeda', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_aluguel', models.CharField(choices=[('Moeda', 'Moeda'), ('Cedula', 'Cedula')], default='Moeda', max_length=2)),
                ('cor_toalha', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='itemtema',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Endereco'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='nome_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Cliente'),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='nome_tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tema'),
        ),
    ]
